mediatheque/urls.py
from django.contrib import admin
from django.urls import path, include
from mediatheque.views import accueil, connexion_superuser

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', accueil , name = 'accueil'),
    path('connexion_superuser', connexion_superuser, name = 'connexion_superuser'),
    path('membre/', include('membre.urls')),
    path('bibliothecaire/', include('bibliothecaire.urls'))
]

membre/urls.py
from django.urls import path
from membre.views import accueil_membre


app_name = 'membre'


urlpatterns = [
    path('accueil/', accueil_membre, name = 'accueil_membre')
]

templates/connexion_superuser.html
{% extends 'index.html' %}

{% block title %}Connexion{% endblock %}

{% block content %}
    <h2>
        Connexion bibliothecaire
    </h2>
    <div>
        <form method="post">
            {% csrf_token %}
            <label>Identifiant :</label>
            <input type="text" name="username"><br><br>
            <label>Mot de passe :</label>
            <input type="password" name="password"><br><br>
            <button type="submit">Se connecter</button>
        </form>
        <span>
            <a href="{% url 'accueil' %}">Retour Accueil médiathéque</a>
        </span>
    </div>
    {% if messages %}
        {% for message in messages %}
        <script>
            alert('{{message}}')
        </script>
        {% endfor %}
    {% endif %}
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Médiathèque{% endblock %}</title>
</head>

<body>
    <header>
        <h1>{% block h1 %}Bienvenue sur la Médiathèque{% endblock %}</h1>
        <p>Choisissez votre espace :</p>
        <ul>
            <li><a href="{% url 'membre:accueil_membre' %}">Espace Membre</a></li>
            <li><a href="{% url 'connexion_superuser' %}">Espace Bibliothécaire</a></li>
        </ul>
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <footer>
        <small>
            © Julien Chauvin
        </small>
    </footer>
</body>
</html>